apiVersion: v1
kind: Service
metadata:
  name: tiermaker-app
spec:
  type: LoadBalancer
  selector:
    app: tiermaker-app
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tiermaker-app
spec:
  serviceName: tiermaker-app
  replicas: 1
  selector:
    matchLabels:
      app: tiermaker-app
  template:
    metadata:
      labels:
        app: tiermaker-app
    spec:
      containers:
        - name: tiermaker-app
          image: docker.nies.io:5000/tiermaker_app:latest
          volumeMounts:
            - name: tiermaker-app-data
              mountPath: /app/server/data
  volumeClaimTemplates:
    - metadata:
        name: tiermaker-app-data
      spec:
        accessModes: ["ReadWriteMany"]
        storageClassName: "nfs-client"
        resources:
          requests:
            storage: 100Gi
