#ENC[AES256_GCM,data:eU2XgOxfDdH/07jf+0e6gZxwVlwqCxsbcMxewa4vpVyfEo4EDNYSbudf2sH9AEVTJYdbpJYn/l+v4wF5WKH2j6BdWcDBSg6NEg4=,iv:Z3cdWtdgeslJJu0FErGC+655TaS6qkdDpiT7KKlPG3w=,tag:DBZDyn2JT83+frYbRrqA6g==,type:comment]
#ENC[AES256_GCM,data:K9jNbGfQ855IWFmgZ1/5jEczFncUcv53EDZIHnrRqqp0qeQLKvsgQfDtaTRKZ17c9LLnd8mqmlCVk2G1+32oSxuoPaY=,iv:TnSmnBnizX4izxakF8vGwBe1i4GEA/iVSXBgJX6wt54=,tag:MAM9xf/v855HbbdTOtIeZA==,type:comment]
#
#ENC[AES256_GCM,data:I61y3AZdrCrwlmZn5gQuLJE9hGFZwSHC7Rj6Zw==,iv:9sw3IWL7Bifkp/uLlNPiNh2e4DOr7PXBuwNN3cNtYxw=,tag:D8MsnoCwzai7p+4dQhCoZw==,type:comment]
#
#ENC[AES256_GCM,data:wgHcbacl/U0HkV61hXxhjVJvvnNE1jBSr4g=,iv:2CBeJozNOIL/Uhlr6LQ9ejTwoSrCxOMSq6WTv+Lgcb0=,tag:u/U8bOi0yxZ3sMf7A7u4Dg==,type:comment]
apiVersion: v1
kind: Secret
metadata:
    name: obojima-tools-secret
stringData:
    #ENC[AES256_GCM,data:9gqepBiKDc6yEXmt1mX6yUgwmWMZy+SJae1O5ZiZQXcsS9aeZ86yutExdQs4foHkAOvWbJTUatBrX7PRMN6WxfTmQUgU7q5CwrI=,iv:AmXTlGMpwqwM3it1RN19s0PQeaWXWKmk6WaHVIT7Ftc=,tag:FeBp26R4Q4OCQGNs8PgXLQ==,type:comment]
    #ENC[AES256_GCM,data:NcKz/glefcfKAcvJhCcsOxSEjeKLOxtZ99yBb5gW2RK/4GYLmI+xEl2BNldUVyYnbrwT939kOohuDYkMfBsUZb/bY2QTte91smo=,iv:wMmVA4MwihmA5mr6K+3MM4X2BEUWaEtT/wLFeJoE91E=,tag:JcThFwULgovS/wWskYzb3w==,type:comment]
    FOUNDRY_RELAY_API_KEY: ENC[AES256_GCM,data:e+ZkSGGMaluC1FqyWh+5DdjAiVp8rzsHZowgscdqrEUik6q5FBw0VKoJecc=,iv:KEjjppSAYchaneYEO1orLvf7PQK0Ne1VpBIoBJYwX7M=,tag:Zq2PtWq/Wd4lWtia5Dqh/w==,type:str]
    #ENC[AES256_GCM,data:AqS9Lo6c5lv0qc2OlgVnXbaStPM9cyZAlhgOz/xqzSOWUnpw658BtcjaDLv8nDf10AGEFvn4ETJYbjJQcW6gw/SMODU=,iv:Ty9BuMt3aRx1j0T6R+9Vm+qHul1HfAVbn1gJL+OXAd4=,tag:kcTxDSJgOsSftPmyssZPfA==,type:comment]
    #ENC[AES256_GCM,data:Usbt5tEkCpzquq0QnM491LLoyRb9Y4UIdgHCVz8eaubAhY+AV+v85WDLZQFuq43DUTYK,iv:YEa7nSpARbkZpmwkYim6ck+yM5oCmpsVmM/d78liyxY=,tag:XzntrDeYkmBe36iafoKXUQ==,type:comment]
    #ENC[AES256_GCM,data:/nA8NKBCZaYPq3ecXADSU922+yHSgwdudJ2wrMsNfBW8x5vkgxbbLzbnbQ==,iv:T/7a6O9kiUc5LeMsxfZWNvB4MTjqwqVAQXB43WOzbBA=,tag:zrEuYmsXHTcrmIGLPEBXnw==,type:comment]
    OBOJIMA_GM_TOKEN: ENC[AES256_GCM,data:7jWT96MnCJcbP5Nz8rKGUqNQg7To5h1uwSQpR9Abj4p2vPItA2GN9nAJeBY=,iv:NCQgkTZ3JMY7yrOYYAq/0GRrG7T5dBKv2faki+gl1PU=,tag:7Yz/ZAuJXj7ZT4Ipj5RgXw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age146ew5u7ufdeqf80ehh79hmcg93mpyttpzq52erdu769f6wm7xass0amenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMbEFMNFJCVnRyMjBHeWxX
            L0J3TTRrTW9UcElMcDFPSjZjU0NHckFqM0FRCllQaDRUSDFtVTgvb1ViN1F6YjY1
            RmpGVFE3WVl2dm1VYXBwRy93RU1Mb3cKLS0tIFpMZXhTMzRsN2J3dmd5R2ZYY2l6
            SFNaSCtIa1h1bG1zK3pmR2VYTGtvVGsKjcTdwSKm1q6/Bt0KbRqyJf/YlaSFJUEZ
            bWgdvA0A0DfVG5VnJsgpn0t0dEU8H0DqP6YNaXo2mu8UZqGuoz9HFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-25T20:04:42Z"
    mac: ENC[AES256_GCM,data:WtjhD887cmQmXSaEHodUqkR/nP7Sb9psvVSSRP+Gm6zhvXW/DBUCC4gkY/iQilgLwaHfY2WXG7lPmyA7jVSOqp9PGKhmQJguJ7Nd/hAcz5N0z99+mx7HOV40QHMp2F+ztY2KXVoWEuLSm7Ixfwcif+a+8ZdEyJpx/djikp+bees=,iv:kZvW7YQ55KqKMEhjE1vUNlrPGZZ5oTzAfKuYfg+m4ls=,tag:I2RfguLOfTIZFTB1RsFAxQ==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.9.4
