#ENC[AES256_GCM,data:7RfVGobjN9yH6LGZnomEeLS3gZSsp+3pkra3WhAVh7d0u7/Ur3eFTF3B/QjHBqz+GZN6QYhUJY/pxCoWyM6uGaoTyR2oERtZ5W8=,iv:1DtuYZnKrwhy4Ps2MnACvw56MqO41SzowttEOXqxg9g=,tag:WdeusnJRTHtdAomjpXXiVg==,type:comment]
#ENC[AES256_GCM,data:h/z3hg9YwmRHG6xGjqHD8+sebEomj1kAgNXJcZi2CG093+MZPHoqOyJ4xKmf2tFWp0F0zZrZcBeI8bCGlep6pEjR1Nw=,iv:cuhEk79NNA40l+CBIc31IGJWmibOcXOrsaKUnhZNeyg=,tag:CDfcF3niQJ5gaFcHUNr1hw==,type:comment]
#
#ENC[AES256_GCM,data:0AQBd1C7QZuGR/dfvDj2iweypRJmh9qWyvAvbQ==,iv:ykjlHbtKxrykCsawwBBGdJOm9iAsJTUJdSjMNRa3jmI=,tag:2TubJDoZtqqUGWk6bx9dnA==,type:comment]
#
#ENC[AES256_GCM,data:Ay5H1+BYWV8cNim6jkVHMlv0bKivnMWc6h8=,iv:daabqaRGCzBYkaloKG/04jP47v0o+Hclkn4p30zEyEg=,tag:Z+mr54dH2zbhQRUtFTpxoQ==,type:comment]
apiVersion: v1
kind: Secret
metadata:
    name: obojima-tools-secret
stringData:
    #ENC[AES256_GCM,data:1jpVgdOC+nylR1FsI5bIvdWb7DJ0R9hS6NjWgiO7iom6Kcbf2ISSZ3gjoUhYyv3e98/Wx9aWp6temqf00Wo6jyI0mEvzSq3Cng8=,iv:n1MmiM88IMHHKv2tpbL6rvgJzzz2CYc4s3OsYUjhmUA=,tag:dJZqrj1WlpEbjb8tCkUWUA==,type:comment]
    #ENC[AES256_GCM,data:yrm23lK1Gi8DX9wqsepkZn9v7HBAybZK7hKTXR8THIoraIQhCnM5mxOIRBwqaWLL2cYoRXARoVozIc0ojVCcHM9Pw2SmJOgGlNI=,iv:7gWWZnppQrGRv3SqE6SILVocnZaySKBEgRynvI8FwSc=,tag:Ev0yrzU/0tfO0c4E3mnqaQ==,type:comment]
    FOUNDRY_RELAY_API_KEY: ENC[AES256_GCM,data:YPhNYf12QzXI9Ax2Uy/FGbvLppTWnU7y9xaDOMHev/yX9hFm2YGX9onhYxWRx3jPsbsoY5wwg+H0pse+i3TPhQ==,iv:f9r/fnY6EeNmFP8gPzzfI6KBbNRUsEgT4y7KPSqpRDM=,tag:DdvDdVoHt/NmgprW/HgNCw==,type:str]
    #ENC[AES256_GCM,data:LwfBOZaK+eMPXt0XOMW8PffefLuIXQbVydfQw+q1nDivy5l7x9+ypdElkikIUO/1Mx3p3trRuvb4ZqzC+68ZcsTnt6I=,iv:4JDrwG18gHfqAaT9wT3g+4VC7IhdNUFtSN9SY8mvPuQ=,tag:w6XzCFMaDDoahTwotWN/Og==,type:comment]
    #ENC[AES256_GCM,data:fFTwt9K/1c0VSdFaQAtVvB77rebu6BRIKMiZLpGLYjr2xHjbIAm2N3xVZhx4X9O9zP3P,iv:0XdHaysG3ntD406gzF55DhW6OMnzYjhqJT77OSZrOPI=,tag:ES8B9WCQuB3k6NhAtxJj9A==,type:comment]
    FOUNDRY_ALCHEMIST_ACTOR_UUID: ENC[AES256_GCM,data:1agewC6rhvYol4ikiFj4KwTgnO/xwQ==,iv:/nPvMcZs1xSDi/gnERm/zW/eLt1LvLPF+OvXiqOCTHo=,tag:TNZkvjBJBVxTzzXIKakihQ==,type:str]
    OBOJIMA_GM_TOKEN: ENC[AES256_GCM,data:LqbxEV9zxgUj+jqpkv6qeF9oiGoa4n4mNiHZp+ni0KUDht5HVbLPUXi4vAk=,iv:nnhDrecrm/i5XERDYeLNXy/ZurCsvMdxwGWZjhg2lhc=,tag:tFt8B1t6MKw01aTVzNhROQ==,type:str]
    OBOJIMA_GM_EMAILS: ENC[AES256_GCM,data:pcmG9NyYdnbCZLTW5dYngcM3mqA=,iv:rQtFhzffTRA+XXuM0uax4Cu0r7Kq08nsdICDYIQOurI=,tag:gWvGhduLF9POzIHiPqaTTw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age146ew5u7ufdeqf80ehh79hmcg93mpyttpzq52erdu769f6wm7xass0amenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5T21VakNsamREZGZHekM4
            aGx4V25CcFo1KzYzZjNVWW1QMEhpNnpwcndFCjVPaEt3YjMvSVBXUWU3Z1hEMEVT
            eklLOW05YnBpaTdSN2pFSjVZR1c2TEkKLS0tIGNWL0tvWWZMVUhrYnduUUFQdkpx
            UkZlVndiOTVaLzRWc0ZlbVUrZ0FXN1kKYMTrQg/SOCb6TKaDxnpxFPsojYhidsD+
            hRUfvITo/nIJNukTAAeo5WiURPE3xFeGXprdYhDvWLPji8LTtBG4SQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-26T05:34:29Z"
    mac: ENC[AES256_GCM,data:JMUqxRY9AeYEEuBR27w/xcyOrEiefAK+qH/vqWffCzDdJqYhzoFHUS3jpoZNR1dhRZkkjyNhYb/OneDIQJOvKmAEfV7k4tQzpxJff+SHset/6ES98mSena34vYar1G2LYTd8yOAoSxakY7hi+1pP+zIqQCHtBtVZQwqtTlqlLh0=,iv:mYOgc+PGv5rUnutmMxwYDnQX9cM2rO8/TOuISR9Tpwg=,tag:/5jaV1bzj9eoCq26NvzgNQ==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.9.4
