apiVersion: v1
kind: Secret
metadata:
    name: foundry-restic-secret
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:xzAcd9j4CNE6umki5uaglFBY1UQEIvVU+bPGY/QNF5tGrT5HW8EVSJcOhcQ2jcoVlNRmHWRCvXqPgzJp/NjB,iv:5pnf38uxeXQTPP9aSnHG2p6gz3OtHlRb8nW8zCua/h8=,tag:khv7018QLYNGf4ZIF8i2ww==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:KHakZ1EzZOrG2TdF3U/QXTv3fEvRa6yb,iv:lryFa272UGKXOTpjUv6bN/Elozp1+mTWoZGAsYpThsY=,tag:GB/Ooios+XbnYxmffILONQ==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:R0+wEWiBifKXPQP4Brf8PTTshozkvcoAUw==,iv:JFNhwECPPuTBLBWpOKOxE+FWdeHa8YZg3wjjuid8Ncs=,tag:k471PdE+jsCd7BC1jGsg0g==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:MHj5VeUVxOoG81FasikBIGBw6pyyAHE80epF+UQDfw==,iv:BkJrMSHLcBhzq/U+hKgb8RiN0pE2nu+jIW8wfngCcFo=,tag:WeRLg3Ffu7GFFNR0RRy7TQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age146ew5u7ufdeqf80ehh79hmcg93mpyttpzq52erdu769f6wm7xass0amenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEYmpVWnkraUQ5S1ozRGRH
            L3FDazRZMlBUVjJQaExrY2FSS0phMVdJWWxFCjVkYlZiZDMrdXZrZG0vdCsrY0RF
            RjZmMUpPdCsybmtSWCtiSmlZZGhxYVUKLS0tIGhtVXErbUNaY0xmL2xVQUtlcXpq
            VklCbkxySXRMM09iOG83eURnRlNaaTQK8hmEaIEM9KlFzoiPyn3oSCuXUz8WKGXy
            d4CTpLJl/IcXbV3XNVVD1hFHYTIQmws2qkaMtF6gieJlsEmFpO6l/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-03T22:58:38Z"
    mac: ENC[AES256_GCM,data:L0Qba1bzT7a5YNJbAPthPEowzr9l1KdPA+xpJ/QwdydrUyJUDGPUawLlDwkffM6vwsDqd+FlsyzdtS8fqeIIuEGomShuauSEtI8bcdW/k9go+FjbESibz0L6k2TlZyxwA8MUEXeNrEiE03cOXEGNdm78rWq/PO5PRsdwrAF/cus=,iv:lEWbTolMMhSRKYS0TXheEjdgpVBPaT81X9kqcz2yhrY=,tag:r0RswiPnwjuw+jG2YlUQvw==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.9.4
