apiVersion: v1
kind: Secret
metadata:
    name: foundry-secret
stringData:
    FOUNDRY_USERNAME: ENC[AES256_GCM,data:M1lbsoPuV0A7XA==,iv:nN/817QANdk6BGlJxJqz2mtQz92CTCcHoyUTOvjGfx0=,tag:AosTVdNX0u7WBpiZKgrVPQ==,type:str]
    FOUNDRY_PASSWORD: ENC[AES256_GCM,data:/w6nNk2v9OefLifKJcpkDFlCDr4=,iv:fwBHC5TKlHEQoppuFkcMEKzjKuvs51tyy3YVA7fYQJc=,tag:8IWctxssLtlOTsANNDUoiA==,type:str]
    FOUNDRY_LICENSE_KEY: ENC[AES256_GCM,data:eiblM76wKKHPR67zaDvJ8dBKMGr01jVayDvDZb0=,iv:HNP0h5iWb6quWFH3qG01JBXypSJkmY4HPlH/2s8gJvM=,tag:bNaDkPYOi6Y7RUhUm6dsyw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age146ew5u7ufdeqf80ehh79hmcg93mpyttpzq52erdu769f6wm7xass0amenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6b2lIVnMwK3BYbUlWQzVr
            TzYwSnY0bXNwdVI5MWU5UXZ3Q1k0OWNBang0Cm90bjZQQkhtTktwbWdyK2tIYkVp
            bHB0MXFjbkRLTklObHFRcFBnMmZPRFkKLS0tIDVRdUpMcDYxcGU2eW1vY1ZOODBG
            RXowQ2xXOFc1KzVzMFlZU3d0SzlRT1UKdKsSZMVjg3jrpmetH9Xya/k6SUjdmxFl
            ZdRPLgo5oE798pKT3ACEoQc8NY6p0fdNGf124+Ylel5DGOIFvR5icw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-04T00:19:42Z"
    mac: ENC[AES256_GCM,data:21KBbqY5Iioab1352+GuhSUwtvjGM/ndhS5ggtjzPolRnwUOuiGK2BaAB5FHxhGBcUFWOdvUCvZi/fYGNiJ3Zeq10QJ8pC1UNiN8cNfkIwbQKCeX9Zh1b0fcxXNWNtMz+H5zye2fYrIbcvlZyaoUh4tU9VPDT4UWNAmLqSOGzy4=,iv:X/n0P4mQo6rODJLspOvcQ7+7+m1eo21VHrlgW0L7T4o=,tag:FP9ZacXR2CvfyQWoqqjIug==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.9.4
