apiVersion: v1
kind: Secret
metadata:
    name: foundry-secret
stringData:
    FOUNDRY_USERNAME: ENC[AES256_GCM,data:M1lbsoPuV0A7XA==,iv:nN/817QANdk6BGlJxJqz2mtQz92CTCcHoyUTOvjGfx0=,tag:AosTVdNX0u7WBpiZKgrVPQ==,type:str]
    FOUNDRY_PASSWORD: ENC[AES256_GCM,data:/w6nNk2v9OefLifKJcpkDFlCDr4=,iv:fwBHC5TKlHEQoppuFkcMEKzjKuvs51tyy3YVA7fYQJc=,tag:8IWctxssLtlOTsANNDUoiA==,type:str]
    FOUNDRY_LICENSE_KEY: ENC[AES256_GCM,data:eiblM76wKKHPR67zaDvJ8dBKMGr01jVayDvDZb0=,iv:HNP0h5iWb6quWFH3qG01JBXypSJkmY4HPlH/2s8gJvM=,tag:bNaDkPYOi6Y7RUhUm6dsyw==,type:str]
    FOUNDRY_ADMIN_KEY: ENC[AES256_GCM,data:YQVgbsTJKe13bnFRMA==,iv:Y/eqnklQaWO2nS3MjYtAUQnq0PEnY495po+2WulKXNI=,tag:nz+6dKcBsNsFOg9mcTLghA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age146ew5u7ufdeqf80ehh79hmcg93mpyttpzq52erdu769f6wm7xass0amenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6b2lIVnMwK3BYbUlWQzVr
            TzYwSnY0bXNwdVI5MWU5UXZ3Q1k0OWNBang0Cm90bjZQQkhtTktwbWdyK2tIYkVp
            bHB0MXFjbkRLTklObHFRcFBnMmZPRFkKLS0tIDVRdUpMcDYxcGU2eW1vY1ZOODBG
            RXowQ2xXOFc1KzVzMFlZU3d0SzlRT1UKdKsSZMVjg3jrpmetH9Xya/k6SUjdmxFl
            ZdRPLgo5oE798pKT3ACEoQc8NY6p0fdNGf124+Ylel5DGOIFvR5icw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-04T00:24:00Z"
    mac: ENC[AES256_GCM,data:d2IjNpYBCCA5jv865O8GAqV+UC22yvuVIlbnIF/rEEIgxJUpuj2HW+pQE052gD3lFHxbALVTiyTgqd9AN+6FkBZliWNcvh082k0+MQTbkVhne9CwY2B0F/JVmu1cvX2pSIv4lmom5EcUexe0lSJzZLT6InROHcLCcKIIqHXfeVE=,iv:7AidbhYQmNqbrw/QQotjB8UQiFmv22IuJ8Xm204jcis=,tag:8YMQcQSE37JqtH0J0Vh2Zg==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.9.4
