apiVersion: v1
kind: Secret
metadata:
    name: foundry-secret
stringData:
    FOUNDRY_USERNAME: ENC[AES256_GCM,data:M1lbsoPuV0A7XA==,iv:nN/817QANdk6BGlJxJqz2mtQz92CTCcHoyUTOvjGfx0=,tag:AosTVdNX0u7WBpiZKgrVPQ==,type:str]
    FOUNDRY_PASSWORD: ENC[AES256_GCM,data:/w6nNk2v9OefLifKJcpkDFlCDr4=,iv:fwBHC5TKlHEQoppuFkcMEKzjKuvs51tyy3YVA7fYQJc=,tag:8IWctxssLtlOTsANNDUoiA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age146ew5u7ufdeqf80ehh79hmcg93mpyttpzq52erdu769f6wm7xass0amenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6b2lIVnMwK3BYbUlWQzVr
            TzYwSnY0bXNwdVI5MWU5UXZ3Q1k0OWNBang0Cm90bjZQQkhtTktwbWdyK2tIYkVp
            bHB0MXFjbkRLTklObHFRcFBnMmZPRFkKLS0tIDVRdUpMcDYxcGU2eW1vY1ZOODBG
            RXowQ2xXOFc1KzVzMFlZU3d0SzlRT1UKdKsSZMVjg3jrpmetH9Xya/k6SUjdmxFl
            ZdRPLgo5oE798pKT3ACEoQc8NY6p0fdNGf124+Ylel5DGOIFvR5icw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-03T22:49:25Z"
    mac: ENC[AES256_GCM,data:r1G7HX7PCPH8N0B2ajUuCO7f10L84jZqUR3NVtqP7S5uxvWdq20HGyH4AThxY585tj8kd+xn8UmOZkznCjiiYLqaPlSgZUJfyqEdRVDGsEbnL2Atu5556dxWxDGDTmT+RdZvuYd00oI8aCEF8mIzkmPzmbxST6KyBD9tbRaC1Gs=,iv:sbou7XlZGTK+awyu3YuXizYw70CYHLhwEYL6GwDla2E=,tag:8L/B4bAz+JGgpnFo4XvDTg==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.9.4
