apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: smi-ost-bot
spec:
  serviceName: smi-ost-bot
  replicas: 1
  selector:
    matchLabels:
      app: smi-ost-bot
  template:
    metadata:
      labels:
        app: smi-ost-bot
    spec:
      containers:
        - name: smi-ost-bot
          image: docker.nies.io:5000/smi_ost_bot@sha256:257f104987783625aef12ecc12940a8c7e3c107059bdf12faa2b252672cd5eed
          resources:
            requests:
              cpu: 500m
              memory: 500Mi
            limits:
              cpu: '1'
              memory: 1Gi
          ports:
            - name: admin
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: smi-ost-admin-access
          env:
            - name: ADMIN_ADDR
              value: ":8080"
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: discord-secrets
                  key: DISCORD_TOKEN
          volumeMounts:
            - name: database
              mountPath: /app/db
        - name: backup
          image: python:3.13-alpine@sha256:1a63a53928ce53d2b0baf08092a703f4840ac5dfbd61fd48802dbf48e08c801e
          command: [ "python", "-u", "/scripts/backup.py" ]
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 200m
              memory: 128Mi
          volumeMounts:
            - name: database
              mountPath: /data
            - name: backups
              mountPath: /backups
            - name: backup-script
              mountPath: /scripts
              readOnly: true
      volumes:
        - name: database
          persistentVolumeClaim:
            claimName: smi-ost-db-local
        - name: backups
          persistentVolumeClaim:
            claimName: smi-ost-backups
        - name: backup-script
          configMap:
            name: smi-ost-backup-script
  volumeClaimTemplates:
    - metadata:
        name: smi-ost-db
      spec:
        accessModes: [ "ReadWriteMany" ]
        storageClassName: "nfs-client"
        resources:
          requests:
            storage: 1Gi
