apiVersion: v1
kind: Secret
metadata:
    name: smi-ost-restic-secret
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:LbMr9ajc4yEXdGFoMQW3jKhK2r8apTxIYIeLTZwG8iDBDkdO,iv:PAYXFGrDXOL9Z2+ZZder9MkN5jIoe5kzFwTiRV6gz14=,tag:Ve1aBgPZ0/WzDKwTkhIFNA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:8Gt1lheZV5tkrWtGA/hXdZcFBj9K3qgoi15Z47b8iDXXGP0WTFCy54nTyjU=,iv:p50qT9VA42rQ1tUCJ6hnHNGLLqLU4U5NEvMaiFLl6gw=,tag:n/GPZRNyF7yb14MmjH9Y2w==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:RIs8iFpM5Yxvv40WL8ks3fHZYGUpeL4qXuoys2zDMwxm/F5wiBF47BAEJr+M6wcoXYN4CpqCq3nAMj3BfvLLCrrwaQNjb2Y1dypGUyOGVNErxAfDw9GqMg==,iv:FuHXSGhg/ozNJPdmAh2pcWrUn2nazOZlzy9mhTWxzZE=,tag:NQcCXuklOP1kVZ4z6cdMnw==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:sB2UgKVpWcjzewxIMa2cY8vurvGPZEIUXb3Gcik5sHJ5Lum5lmqBlbWax4/WEZSEZvqYvd9dzoFc/hXPEPoXVJJZM+RJahsm883vjv4CoeBfIP8IxRtDcw1uNn0=,iv:8br4KX7vFqIdDqd4MqCIYg9fZISM0boiMOmvT/3UOKQ=,tag:VgKwrpNYhf0zPQ8hF3PslA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age146ew5u7ufdeqf80ehh79hmcg93mpyttpzq52erdu769f6wm7xass0amenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0c2d5TkhZeDZkRjVpMUFr
            a3p1K3FCRjFrMVFpZ1d3SnQ2WHhpUllWaFgwClU5ME1XRTZCTUdQM1QrZmljSzIx
            OEVpdmgxeHJtRHhEcVRoTUplREN3aW8KLS0tIDJGNXdwWHdmWlNBQjVnTkFlaHFn
            VHE0bmdFYnhjUG1PWmxPRVdRS0VCWHcKiQdOwjoJ4StEnEMIWLNWeYXrP/bKDhw9
            Vs4jX9AmB6g93+FRKsIU8BiHJvBeLt8Te2KVHoxe1PTs2M8rpVIkjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-20T15:55:19Z"
    mac: ENC[AES256_GCM,data:3uD64KhTLOgjL16Ap1RktkPsAkYPi9qvtsJ5cgwjZE1vN4JuChn8Jkp9NoPhcDtxuYLHtB+QpaIyIje3TvtDD2MYYcJz2swczOyp6MdULoX/P4ouk2dxJEFekL8u/l1Rctw5O2VwWCq+t0RFCiwNaaZg5PAZa8GT47d3ssXppGc=,iv:2tWmqi1GdXdVJxJKh47P+u9MQtExCGtjnuPrLV8xrzg=,tag:iWpb0V8fZqzEJVV+CzEuiA==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.9.4
