apiVersion: v1
kind: Secret
metadata:
    name: discord-secrets
data:
    DISCORD_TOKEN: ENC[AES256_GCM,data:Ij9TRwZBaUwyjfuOqnDnKx9WSUL5HnhZQBjaB2+rzlK6VwlT0rhLS1K6PK8ViTvpDGMUg7I39FXz8s5FYhr8gkTDV208CZ9SR9tJOFl7qxDzXf+JYQTPfvmXh8xUnUPe,iv:6Zl4HNfL0hQU509RM49zXVg9rpayNQuOwGVxE+/PG7Q=,tag:DZs758hSimjbwSxdUP98PQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age146ew5u7ufdeqf80ehh79hmcg93mpyttpzq52erdu769f6wm7xass0amenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzK1Z6NHBsWXkwNStyN0to
            WGpxd29wb280Q1FGUjl5SnlZSEdCcm5LOEF3CkJ2Q05sQW9sN1ViSjdaalRsUloz
            RkxMSXRwUXNtdTJoZjFrS2VrbnZRY0UKLS0tIHFNZ3V5VTJFcTNDSmIxdHFDblh5
            L2NWK09MQVFBU0ZrUFd3WDZENGtUdGMKpM4bBhFOUg/PjxQz7VGjUg0i4MNOxNre
            Lrdi9sU7qSGSKDBwN09y/GvaJXXsdfqf8EdHbhZTAfwaublxfAo/PA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-20T15:51:50Z"
    mac: ENC[AES256_GCM,data:wG9DhTt877KZGCUxV0pq2t7elqbgZuKgP+HDIzB1UZ3FiiBM6UJTqhLtTAGB1ZxGDN4RbB00i2lOqZgyu9G7tx1BWIy+RR8fu+EHzdSxX3WM6huSpmVKynlGrdoZvlsJ3VavKgoxvwHgKwUVVxiUbmy0NbMywlYns1kVIF0FhJU=,iv:QIlopSMIxIud4s6dmttoLI5H9Df1dNDmm0nqBv7MPNw=,tag:hnE/8qjrLTPMBz9422bHlA==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.9.4
