apiVersion: v1
kind: Secret
metadata:
    name: foundry-rest-api-secret
stringData:
    CREDENTIALS_ENCRYPTION_KEY: ENC[AES256_GCM,data:j6iVbJUfbhKdFVmshbqu7Jp38O0MN3sZfrUtnqNUhjirXmGRXNyySnojpqJXjZUSH46paS5JkpyT5GtbJF/TkQ==,iv:8RNYt/sT3+cUHraCNsnyX9E1AAclIo5JKB4PKQgVc5Q=,tag:7gaR1rB8zirsc06E4v6ZaA==,type:str]
    ADMIN_JWT_SECRET: ENC[AES256_GCM,data:oSOxYQD9d15b+0Vw/+0z0p+6HfJfhrm8KWqdqSUCvCHzEDhVYt+RQXAvV5A=,iv:p7LOWidf+vtztIW+Z14W6NUJfxuVAakNW6DRzgB2bAY=,tag:hXusD+O1ynClAmRXZN3pzw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age146ew5u7ufdeqf80ehh79hmcg93mpyttpzq52erdu769f6wm7xass0amenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4L1ZzZ0JhZmZETXlFa3l6
            S0dSclpoWE1Zd0RiRmVWU3BNRjk0MGludG1JCkI4MUVuMFhGcUI1eHppcVRWd3B0
            NUdtSlUzTElqZWp5NFRvekhaeVZVazQKLS0tIC96MTViR1YwTG5ZUkx5L2dYOGNh
            NzFuaS9aL3BLMmNzdkQ3RFVHYmx5Uk0K7zf/l5Sge3dkFzYEkeuxBA1huzDAJ8RE
            AJf6WJY0BxUle/iX21EQVLvYTkZ/EtR8zW2zrw5qVgm4LNlQNjQ8WA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-25T20:00:03Z"
    mac: ENC[AES256_GCM,data:psGngMpCnvvaVjhAK0qIW2lHrF5CvKwxlCb2xlOPVtkvJSHleW9GWgJLsriyxTd00ssQe4s7sf3odmcMehbWdjJ7/DA6klWkL2RAimuwDh7+CZhvwS9arQYqrHYWAvNOQqQqsgjztZSF9avHFgT5nn2ZO4dNafb4QLwyf4SLluA=,iv:ukXB6FFnlqBGBEZDwEH34KMbcwrzCbR9ujsyR6sLXm4=,tag:y7J9l3N7o/IXcqZ7YYA8ng==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.9.4
